name: Deploy to Render

on:
  push:
    branches:
      - "**"
  workflow_dispatch: {}

concurrency:
  group: render-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger via Render Deploy Hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "Triggering Render deploy via Deploy Hook..."
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"

      - name: Trigger via Render API (fallback)
        if: ${{ secrets.RENDER_DEPLOY_HOOK == '' && secrets.RENDER_API_KEY != '' && secrets.RENDER_SERVICE_ID != '' }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering Render deploy via API..."
          curl -fsSL -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys

      - name: Fail if no Render credentials provided
        if: ${{ secrets.RENDER_DEPLOY_HOOK == '' && (secrets.RENDER_API_KEY == '' || secrets.RENDER_SERVICE_ID == '') }}
        run: |
          echo "Missing Render secrets. Set one of the following:" >&2
          echo "- RENDER_DEPLOY_HOOK (preferred)" >&2
          echo "- RENDER_API_KEY and RENDER_SERVICE_ID (fallback)" >&2
          exit 1

